In [1]:
import torch

torch_array = torch.empty(5, 3)
print(torch_array)

tensor([[7.1633e-39, 9.9184e-39, 9.0000e-39],
        [1.0561e-38, 1.0653e-38, 4.1327e-39],
        [8.9082e-39, 9.8265e-39, 9.4592e-39],
        [1.0561e-38, 1.0653e-38, 1.0469e-38],
        [9.5510e-39, 8.7245e-39, 1.0194e-38]])


In [3]:
rand_torch_array = torch.rand(5, 3)
print(rand_torch_array)

tensor([[0.1139, 0.7852, 0.9114],
        [0.2130, 0.9920, 0.5986],
        [0.5605, 0.5696, 0.0325],
        [0.0387, 0.6651, 0.1473],
        [0.4038, 0.0484, 0.2668]])


In [7]:
zeros_torch_array = torch.zeros(5, 3, dtype=torch.long)
print(zeros_torch_array)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
tensor_torch_array = torch.tensor([5.5, 3])
print(tensor_torch_array)


tensor([5.5000, 3.0000])


In [2]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
y = x + 2
print(y)
print(y.grad_fn)
z = y * y * 3
out = z.mean()

print(z, out)

out.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
